import { notifyToast } from './toast';

interface ErrorReport {
  timestamp: string;
  version: string;
  platform: string;
  userAgent: string;
  language: string;
  theme: string;
  error: {
    message: string;
    stack?: string;
    componentStack?: string;
  };
  logs: string[];
  route: string;
}

const ERROR_LOG_KEY = 'autodub_error_log';
const MAX_LOG_ENTRIES = 200;

// ─── Runtime log buffer ───
const logBuffer: string[] = [];

export function captureLog(message: string) {
  const entry = `[${new Date().toISOString()}] ${message}`;
  logBuffer.push(entry);
  if (logBuffer.length > MAX_LOG_ENTRIES) logBuffer.shift();

  // Also persist to localStorage for crash recovery
  try {
    const stored: string[] = JSON.parse(localStorage.getItem(ERROR_LOG_KEY) || '[]');
    stored.push(entry);
    if (stored.length > MAX_LOG_ENTRIES) stored.splice(0, stored.length - MAX_LOG_ENTRIES);
    localStorage.setItem(ERROR_LOG_KEY, JSON.stringify(stored));
  } catch { /* ignore */ }
}

export function getRecentLogs(): string[] {
  try {
    const stored = JSON.parse(localStorage.getItem(ERROR_LOG_KEY) || '[]');
    return [...stored.slice(-50), ...logBuffer.slice(-50)];
  } catch {
    return logBuffer.slice(-50);
  }
}

export function clearLogs() {
  logBuffer.length = 0;
  localStorage.removeItem(ERROR_LOG_KEY);
}

// ─── Build error report ───
function buildReport(error: Error, componentStack?: string): ErrorReport {
  return {
    timestamp: new Date().toISOString(),
    version: '1.0.0',
    platform: navigator.platform || 'unknown',
    userAgent: navigator.userAgent,
    language: navigator.language,
    theme: document.documentElement.getAttribute('data-theme') || 'dark',
    error: {
      message: error.message || 'Unknown error',
      stack: error.stack?.slice(0, 3000),
      componentStack: componentStack?.slice(0, 2000),
    },
    logs: getRecentLogs(),
    route: window.location.hash || '/',
  };
}

// ─── Open GitHub issue with pre-filled error ───
export function reportErrorToGitHub(error: Error, componentStack?: string) {
  const report = buildReport(error, componentStack);

  const title = encodeURIComponent(`[Bug] ${error.message.slice(0, 80)}`);
  const body = encodeURIComponent(`## 🐛 Auto-Reported Error

**Time:** ${report.timestamp}
**Version:** ${report.version}
**Platform:** ${report.platform}
**Language:** ${report.language} | Theme: ${report.theme}
**Route:** ${report.route}

### Error
\`\`\`
${report.error.message}
\`\`\`

### Stack Trace
\`\`\`
${report.error.stack || 'No stack trace'}
\`\`\`

${report.error.componentStack ? `### Component Stack\n\`\`\`\n${report.error.componentStack}\n\`\`\`\n` : ''}

### Recent Logs
\`\`\`
${report.logs.join('\n') || 'No logs captured'}
\`\`\`

---
🤖 *Auto-generated by AutoDub Studio Error Reporter*
`);

  const url = `https://github.com/LiskinLabs/autodubstudio/issues/new?title=${title}&body=${body}&labels=bug,auto-reported`;

  notifyToast.error('💥 Error captured!', {
    description: 'Detailed report ready. Open GitHub issue?',
    duration: 0,
    id: 'error-report',
  });

  return { report, url };
}

// ─── Global error handler ───
export function initGlobalErrorHandler() {
  // Catch unhandled promise rejections
  window.addEventListener('unhandledrejection', (event) => {
    const error = event.reason instanceof Error ? event.reason : new Error(String(event.reason));
    captureLog(`[UNHANDLED REJECTION] ${error.message}`);
    const { url } = reportErrorToGitHub(error);
    console.error('[ErrorReporter] Unhandled rejection. Report URL:', url);
  });

  // Catch global errors
  window.addEventListener('error', (event) => {
    const error = event.error instanceof Error ? event.error : new Error(event.message);
    captureLog(`[GLOBAL ERROR] ${error.message} @ ${event.filename}:${event.lineno}`);
    const { url } = reportErrorToGitHub(error);
    console.error('[ErrorReporter] Global error. Report URL:', url);
  });

  // Override console.error to capture
  const originalError = console.error.bind(console);
  console.error = (...args: any[]) => {
    originalError(...args);
    const msg = args.map(a => (a instanceof Error ? a.message : String(a))).join(' ');
    captureLog(`[ERROR] ${msg.slice(0, 500)}`);
  };

  // Capture console.warn too
  const originalWarn = console.warn.bind(console);
  console.warn = (...args: any[]) => {
    originalWarn(...args);
    const msg = args.map(a => String(a)).join(' ');
    captureLog(`[WARN] ${msg.slice(0, 300)}`);
  };

  captureLog('[SYSTEM] Error reporter initialized');
}
